"""Structurally valid sample files, built from scratch - AS/NI.

Two places in this repository needed "a legitimate high-entropy file" and both
faked it the same way, with a magic number and a megabyte of `os.urandom`:

  * src/train_behavioral_model.py built `photo_N.png` as PNG magic + random and
    labelled it benign, then built `spoofed_N.png` the same way and labelled it
    ransomware. The two classes were byte-for-byte the same distribution with
    opposite labels, so the corpus was self-contradictory. Measured per-kind
    accuracy: `spoofed` 15.2%, and it dragged `archive` to 66.7% and `clip` to
    80% with it.
  * services/monitor/tests/test_benchmarks.py built its 40-file false-positive
    corpus the same way. That benchmark reads 0/40 - correctly, for the detector
    it was testing, which trusted four bytes. Against a detector that checks
    structure those same files are forgeries, and the benchmark would have
    reported 20 false positives on files no user has ever had.

So the fix is not to weaken the check. It is to stop calling random bytes a PNG.

Every builder here emits a file a parser would accept: real deflate streams,
real CRCs, real chunk and box and segment framing, a real cross-reference table.
What they do *not* contain is meaningful content - the pixels are noise, the
video payload is noise, the JPEG scan is noise that has been byte-stuffed the
way an encoder stuffs it. That is deliberate and it is the point: these are
files that are simultaneously **high entropy** and **structurally sound**, which
is exactly the case that separates a photo from a photo-shaped ciphertext, and
exactly the case a magic-byte check cannot see.

Being precise about what is synthetic here, because the previous docstring was
not: nothing in this module is a real photograph, document or recording, and no
sample anywhere in this project is a real ransomware artefact. These are
procedurally generated files with genuine format structure and random payloads.

    from synthetic_corpus import build_png, build_zip, spoof
"""

from __future__ import annotations

import gzip
import io
import os
import struct
import zipfile
import zlib
from typing import Callable

Randomness = Callable[[int], bytes]

# Words with a plausible frequency distribution, so text samples land near the
# 4.2-4.7 bits/byte real prose occupies rather than at the 4.9 of uniform
# letters.
_WORDS = (
    b"the", b"of", b"and", b"for", b"quarterly", b"revenue", b"report",
    b"section", b"analysis", b"summary", b"project", b"review", b"figure",
    b"appendix", b"reference", b"result",
)


def build_text(size: int, entropy: Randomness = os.urandom) -> bytes:
    """Prose-shaped bytes. Low entropy, no container header."""
    out = bytearray()
    picker = 0
    while len(out) < size:
        # Indexed off a keystream rather than `random` so a caller can make the
        # whole corpus reproducible by passing a seeded source.
        chunk = entropy(64)
        for byte in chunk:
            out += _WORDS[byte % len(_WORDS)] + b" "
            picker += 1
            if len(out) >= size:
                break
    return bytes(out[:size])


# ------------------------------------------------------------------------ zip


# `zipfile` stamps `time.localtime()` and the host platform into every member it
# writes, so two runs of the same builder produce different bytes. That is
# invisible in a file you are about to open and very visible in a corpus: a few
# differing bytes per sample moved the trained model's ROC AUC in the fifth
# decimal and shuffled its feature importances, which is enough to make "retrain
# and you get the same numbers" false. Pinned, so it is true.
_FIXED_TIMESTAMP = (1980, 1, 1, 0, 0, 0)
_FIXED_CREATE_SYSTEM = 0  # MS-DOS, rather than whatever host is running this


def _zip_member(name: str, compress_type: int) -> zipfile.ZipInfo:
    info = zipfile.ZipInfo(name, date_time=_FIXED_TIMESTAMP)
    info.compress_type = compress_type
    info.create_system = _FIXED_CREATE_SYSTEM
    return info


def build_zip(size: int, entropy: Randomness = os.urandom) -> bytes:
    """A real archive: local headers, a central directory, an EOCD that closes it.

    The member is stored rather than deflated, because the payload is random and
    deflating random data is pure cost for no size change.
    """
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr(
            _zip_member("payload.bin", zipfile.ZIP_STORED), entropy(max(size - 200, 1))
        )
        archive.writestr(
            _zip_member("manifest.txt", zipfile.ZIP_STORED),
            "generated by scripts/synthetic_corpus.py\n",
        )
    return buffer.getvalue()


def build_docx(size: int, entropy: Randomness = os.urandom) -> bytes:
    """A .docx is a ZIP of XML parts, and is treated as one everywhere here."""
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr(
            _zip_member("[Content_Types].xml", zipfile.ZIP_DEFLATED),
            "<?xml version='1.0'?><Types/>",
        )
        archive.writestr(
            _zip_member("word/document.xml", zipfile.ZIP_DEFLATED),
            build_text(size, entropy).decode("latin-1"),
        )
    return buffer.getvalue()


# ----------------------------------------------------------------------- gzip


def build_gzip(size: int, entropy: Randomness = os.urandom) -> bytes:
    """A real gzip member - header, deflate stream, CRC-32 and ISIZE trailer.

    `mtime=0` for the same reason the ZIP timestamp is pinned above: gzip writes
    the current time into four bytes of its header, and four differing bytes per
    sample is enough to move a trained model's metrics.
    """
    return gzip.compress(build_text(size, entropy), mtime=0)


# ----------------------------------------------- containers with no validator


def build_bzip2(size: int, entropy: Randomness = os.urandom) -> bytes:
    """A real bzip2 stream. `BZh` is a header services/monitor/containers.py
    recognises and has no validator for, which is a case worth representing:
    the detector's answer for it is "no opinion, keep the exemption", and a
    model that had never seen one would be guessing."""
    import bz2

    return bz2.compress(build_text(size, entropy))


def build_xz(size: int, entropy: Randomness = os.urandom) -> bytes:
    """A real XZ stream - the other unvalidated container in the corpus."""
    import lzma

    return lzma.compress(build_text(size, entropy))


# ------------------------------------------------------------------------ png


def _png_chunk(kind: bytes, data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))


def build_png(size: int, entropy: Randomness = os.urandom) -> bytes:
    """A decodable 8-bit RGB PNG whose pixels are noise.

    Noise is the honest choice for this corpus: a real photograph is already
    near-incompressible after PNG's filters, so a benign PNG *is* high entropy.
    A gradient would compress to nothing and would test the opposite case.
    """
    width = max(int((max(size, 64) / 3) ** 0.5), 8)
    height = width
    # A filter byte per scanline, filter type 0 (None) - legal, and the right
    # choice for data that has no inter-pixel correlation to exploit.
    raw = bytearray()
    for _ in range(height):
        raw += b"\x00" + entropy(width * 3)

    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return b"".join(
        (
            b"\x89PNG\r\n\x1a\n",
            _png_chunk(b"IHDR", header),
            _png_chunk(b"IDAT", zlib.compress(bytes(raw), 6)),
            _png_chunk(b"IEND", b""),
        )
    )


# ----------------------------------------------------------------------- jpeg

# A real JFIF APP0, a real 8-bit quantisation table, a real baseline frame
# header and a real Huffman table. Lifted from the shapes JPEG defines rather
# than invented: each segment's declared length is what its contents actually
# occupy, which is the property the structural check verifies.
_JPEG_APP0 = b"\xff\xe0" + struct.pack(">H", 16) + b"JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00"
_JPEG_DQT = b"\xff\xdb" + struct.pack(">H", 67) + b"\x00" + bytes(range(1, 65))
_JPEG_DHT = (
    b"\xff\xc4"
    + struct.pack(">H", 2 + 1 + 16 + 12)
    + b"\x00"
    + bytes([0, 1, 5, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])
    + bytes(range(12))
)
_JPEG_SOS = (
    b"\xff\xda" + struct.pack(">H", 12) + b"\x03\x01\x00\x02\x11\x03\x11\x00\x3f\x00"
)


def build_jpeg(size: int, entropy: Randomness = os.urandom) -> bytes:
    """Real JFIF framing around a byte-stuffed high-entropy scan.

    The scan data is noise rather than a decodable Huffman stream, and every
    0xFF in it is followed by 0x00 exactly as an encoder stuffs them, so no byte
    of the payload can be mistaken for a marker. Everything up to and including
    SOS is a genuine segment chain with genuine declared lengths - which is what
    a structural check reads, and what `\\xff\\xd8\\xff\\xe0` plus random bytes
    does not have.
    """
    width = max(int((max(size, 64) / 3) ** 0.5), 8)
    frame = b"\xff\xc0" + struct.pack(">H", 17) + bytes([8]) + struct.pack(">HH", width, width) + (
        b"\x03\x01\x11\x00\x02\x11\x01\x03\x11\x01"
    )

    header = b"".join((b"\xff\xd8", _JPEG_APP0, _JPEG_DQT, frame, _JPEG_DHT, _JPEG_SOS))
    payload = entropy(max(size - len(header) - 2, 1)).replace(b"\xff", b"\xff\x00")
    return header + payload + b"\xff\xd9"


# ------------------------------------------------------------------------ pdf


def build_pdf(size: int, entropy: Randomness = os.urandom) -> bytes:
    """A real PDF: numbered objects, a correct xref table, startxref, %%EOF.

    The bulk is a binary stream object, which is where a real PDF's entropy
    lives too - embedded JPEGs and font programs.
    """
    stream = entropy(max(size - 700, 16))
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>",
        b"<< /Length " + str(len(stream)).encode() + b" /Filter /ASCIIHexDecode >>\nstream\n"
        + stream
        + b"\nendstream",
    ]

    out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
    offsets = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(number).encode() + b" 0 obj\n" + body + b"\nendobj\n"

    startxref = len(out)
    out += b"xref\n0 " + str(len(objects) + 1).encode() + b"\n"
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        b"trailer\n<< /Size "
        + str(len(objects) + 1).encode()
        + b" /Root 1 0 R >>\nstartxref\n"
        + str(startxref).encode()
        + b"\n%%EOF\n"
    )
    return bytes(out)


# -------------------------------------------------------------------- iso-bmff


def _box(kind: bytes, payload: bytes) -> bytes:
    return struct.pack(">I", len(payload) + 8) + kind + payload


def build_mp4(size: int, entropy: Randomness = os.urandom) -> bytes:
    """ftyp, a minimal moov, and an mdat of noise - boxes that tile exactly.

    Compressed video really is near-random, so the payload being noise is
    faithful. What makes it a container rather than a blob is the box chain, and
    the box chain is real.
    """
    ftyp = _box(b"ftyp", b"mp42" + struct.pack(">I", 0) + b"mp42" + b"isom")
    mvhd = _box(b"mvhd", b"\x00" * 100)
    moov = _box(b"moov", mvhd)
    payload = entropy(max(size - len(ftyp) - len(moov) - 8, 1))
    return ftyp + moov + _box(b"mdat", payload)


# ------------------------------------------------------------------- forgeries


def spoof(magic: bytes, size: int, entropy: Randomness = os.urandom) -> bytes:
    """A container header pasted over ciphertext - the evasion, not the format.

    This is what `spoofer` in scripts/ransomware_simulator.py writes and what the
    malicious half of the training corpus is built from. Kept beside the real
    builders on purpose: the pair is the whole experiment, and the only thing
    that separates them is structure.
    """
    return magic + entropy(max(size - len(magic), 1))


# Header/extension pairs used to build the spoofed half of a corpus, matched to
# the builders above so every forgery has a genuine counterpart to be told apart
# from.
SPOOF_TARGETS = (
    (b"PK\x03\x04", ".zip"),
    (b"\x89PNG\r\n\x1a\n", ".png"),
    (b"\xff\xd8\xff\xe0", ".jpg"),
    (b"%PDF-1.7\n", ".pdf"),
    (b"\x00\x00\x00\x18ftypmp42", ".mp4"),
    (b"\x1f\x8b\x08\x00", ".gz"),
)
